### ISSUE TITLE
Modrinth/Curseforge?

### ISSUE THREAD

**Issue by MenacingPerson** [soramame0256/showmemydps#1]
Please publish it on modrinth/curseforge, thx

**Comment by soramame0256** [comment]
I started to working for it, but I'm not sure if it be completed.
sorry

**Comment by soramame0256** [comment]
I wrote draft on modrinth/curseforge and requested to review.
Maybe it'll be published after reviewing.

**Comment by MenacingPerson** [comment]
I'm not sure if modrinth/curseforge will accept `show me my dps` as a name for a wynncraft mod.

You might need to change the name, since dps can be vanilla as well and this mod doesn't measure vanilla dps.

**Comment by soramame0256** [comment]
fmm… I think it too.
so I added "a wynncraft mod" to description.
is it not enough?

**Comment by soramame0256** [comment]
Both of them are approved and published.

**Comment by MenacingPerson** [comment]
Thank you very much!! I appreciate it
