### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by MenacingPerson** [soramame0256/showmemydps#2]
If there is no license it becomes ARR automatically. And so, people cannot contribute to it.

Could you please add a license? Thanks a lot

**Comment by soramame0256** [comment]
oh, i didn't know it.
i'll add it.

**Comment by soramame0256** [comment]
added.
thanks for telling me!

**Comment by MenacingPerson** [comment]
Thank you very much!

I don't know much about forge or quilt but I do know in fabric.mod.json there is a license field you should change to MIT

**Comment by soramame0256** [comment]
updated. thanks for telling this too!
(and this will be applied from 1.6-SNAPSHOT porting update)
