### ISSUE TITLE
fabric 1.18.2 plz

### ISSUE THREAD

**Issue by dirtysheep233** [soramame0256/showmemydps#3]

**Comment by soramame0256** [comment]
https://cdn.discordapp.com/attachments/317970591191924736/1118196553778221086/showmemydps-1.0.0.jar
it built on June, 2023 so have the same function as 1.5-SNAPSHOT but it haven't tested so if you use it, it may causes crash.
I apologize for the inconvenience.

**Comment by dirtysheep233** [comment]
> https://cdn.discordapp.com/attachments/317970591191924736/1118196553778221086/showmemydps-1.0.0.jar it built on June, 2023 so have the same function as 1.5-SNAPSHOT but it haven't tested so if you use it, it may causes crash. I apologize for the inconvenience.

it didn't crash :D

**Comment by dirtysheep233** [comment]
ty so much
