### ISSUE TITLE
1.20.2 pretty please?

### ISSUE THREAD

**Issue by MenacingPerson** [soramame0256/showmemydps#4]
Could you please make a 1.20.2 version of this mod? Wynntils moved to that version

**Comment by soramame0256** [comment]
I was working on 1.1.0 for make versions above 1.19.3 work in the same way as 1.6-snapshot,
but it's stuck for a long time,
and I have to implement it to packaging it.
so please wait.
sorry for the inconvenience.
but current source will work well almost same as 1.0.0, so you can build it.

**Comment by soramame0256** [comment]
Released!
Thank you for creating issue!
