### ISSUE TITLE
Crash Caused Other Mod Configs to Delete  

### ISSUE THREAD

**Issue by BlueTheSniper** [soramame0256/showmemydps#6]
Hello, I just spoke with bolyai from Wynntils because my Item UI had vanished along with the whole Wynntils config. I can send you the full conversation over Discord if need be.

He suggested I send this report your way.

I have a low performance system so I didn't think much of the crash when it happened. The game froze and Minecraft closed.

[crash-2024-04-29_01.09.19-client.txt](https://github.com/soramame0256/showmemydps/files/15152065/crash-2024-04-29_01.09.19-client.txt)

Kind regards.

_This feels like I'm writing an email... I've never done this before_

**Comment by soramame0256** [comment]
really..?
i taught it was fixed in 1.20.2-1.1.1.fix.1 but wasn't.
I'll work for fixing it.
i'm so sorry for crashing and it caused deleting config.

**Comment by soramame0256** [comment]
fixed version released.(1.1.1.fix.3)
thank you for reporting it and I'm sorry for it caused deleting your config.
